"""Add Review Model

Revision ID: 8a326415ba28
Revises: d2b4f37bce9c
Create Date: 2023-08-06 00:20:57.560801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a326415ba28'
down_revision = 'd2b4f37bce9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
